### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ericnyamu** [markrjr/Salut#1]
Is there away to load balance between two wifi connections on an android phone ?Imagine being at the CBD (central business districts)with all the free open public wifi.wouldn't it be of tremendous advantage to connect to two or even three one wifi networks and load balance the internet connection?If it can be done with a lan setup am sure it can also be done on public wifi using an android phone.
the best way to achieve load balancing on android is to have two network interfaces.the real one and the virtual one. and have then connect to two different networks at the same time.the second network interface which is a virtual one will be created and connects to free wifi network just like the fast one.

**Comment by markrjr** [comment]
I'm not really sure, you would probably have to look to the NDK in order to gain direct access to the network hardware in order to implement this. Furthermore, this wouldn't be possible on all phones, particularly because the chipset on some cheaper phones actually prevents them from being connected to WiFi Direct and a wireless network at the same time, therefore, it would probably be even more of a challenge to get the device to connect to two or more WiFi networks at the same time, though the load balancing algorithm might by somewhat easy to implement. As an example, the Moto G (1st Gen) cannot be connected to a WiFi Direct group and a regular WiFi network at the same time.

As a side note, you're certainly welcome to fork the library, if it helps you, and try implement this yourself, but right now, that's not the primary focus of this library. (Though it is a really cool concept!)
